kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db
    type: DirectoryOrCreate