kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-data
  namespace: chat-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 5Gi