kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-data
  namespace: chat-app
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/data
    type: DirectoryOrCreate