kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-data
  namespace: chatapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/db
    type: DirectoryOrCreate