kind: Deployment
apiVersion: apps/v1
metadata:
  name: chatapp-frontend
  namespace: chat-app
  labels:
    app: chatapp
    feature: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      feature: frontend
  template:
    metadata:
      labels:
        app: chatapp
        feature: frontend
    spec:
      containers:
      - name: chatapp-frontend
        image: saadzahid/fullstack-chatapp-frontend:v2
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: "development"
        - name: BACKEND_URL
          value: "http://backend:5001"