kind: Secret
apiVersion: v1
metadata:
  name: chatapp-secret
  namespace: chat-app
type: Opaque
data:
  # MongoDB Creds
  MONGO_INITDB_ROOT_USERNAME: cm9vdAo=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4K
  # NodeJS Backend Creds
  JWT_SECRET: ursUS2R529ul9DwOnmgykEDBaaPfRi7JXKO0aAjfxW8=
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6YWRtaW5AbW9uZ286MjcwMTcvY2hhdEFwcD9hdXRoU291cmNlPWFkbWluJnJldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQo=
  